name: xenotune_flutter_dev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.3
  audio_waveforms: ^1.3.0
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get: ^4.7.2
  get_it: ^8.0.3
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  injectable: ^2.0.1
  internet_connection_checker_plus: ^2.7.2
  just_audio: ^0.10.1
  material_symbols_icons: ^4.2815.0
  numberpicker: ^2.1.2
  rive: ^0.13.20
  simple_gradient_text: ^1.3.0
  slide_countdown: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/animations/
    - assets/Icons/
    - assets/sounds/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/Icons/CustomIcon.ttf
    
