// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr3KSlRthJ6wNbj1-XZTBVwNJANLQL2Ig',
    appId: '1:460199195974:web:74b63f10bb4785438e6147',
    messagingSenderId: '460199195974',
    projectId: 'xenotune-fromx',
    authDomain: 'xenotune-fromx.firebaseapp.com',
    storageBucket: 'xenotune-fromx.firebasestorage.app',
    measurementId: 'G-9PTZK8N918',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkbM91R8s7ymlZw2ZIvv0RjihGSc-ebI',
    appId: '1:460199195974:android:e6504d663c27255a8e6147',
    messagingSenderId: '460199195974',
    projectId: 'xenotune-fromx',
    storageBucket: 'xenotune-fromx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRK5soI4CA0w5IXqlHMZop8dxA3XXmME',
    appId: '1:460199195974:ios:5cd20f881aa90bd98e6147',
    messagingSenderId: '460199195974',
    projectId: 'xenotune-fromx',
    storageBucket: 'xenotune-fromx.firebasestorage.app',
    androidClientId: '460199195974-65rsgn6nvtd5biqpl8k9f5b6r00bd2o3.apps.googleusercontent.com',
    iosClientId: '460199195974-sanu38vnidqpbtb8kptt6b8jpcsnhqac.apps.googleusercontent.com',
    iosBundleId: 'com.xenotunefromx.app',
  );

}